import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Luke Dependahl</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Hi, I&apos;m Luke.</h1>

				<p >
					Developer, Designer, and Icon.
				</p>

			</main>

		</div>
	)
}
